Add notifications module base
Kuonakhallah/FitFuel pull request #20
Opened 2023-06-26 15:43 UTC by egorgeberleyn

2023-06-26 16:43 UTC, artemstasyuk commented on Fitfuel.Server/Modules/Notifications/Fitfuel.Notifications.API/Common/Errors/Errors.EmailSender.cs
> +    {
Error message на английском пиши

2023-06-26 16:53 UTC, artemstasyuk reviewed
Reviewed

2023-06-26 16:55 UTC, artemstasyuk commented on Fitfuel.Server/Modules/Notifications/Fitfuel.Notifications.API/Common/Errors/Errors.EmailSender.cs
Error messege на английском

2023-06-26 16:58 UTC, artemstasyuk commented on Fitfuel.Server/Shared/Fitfuel.Shared/DependencyInjection.cs
check

2023-06-26 16:59 UTC, artemstasyuk commented on Fitfuel.Server/Modules/Notifications/Fitfuel.Notifications.API/Common/Errors/Errors.EmailSender.cs
> +    }
поле Error.Message на английском

2023-06-26 18:00 UTC, And1lo requested changes

2023-06-27 17:50 UTC, egorgeberleyn commented on Fitfuel.Server/Modules/Notifications/Fitfuel.Notifications.API/Common/Errors/Errors.EmailSender.cs
> +    }
В дальнейшем будем внедрять локализацию

2023-06-29 22:48 UTC, merged